version: '3'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres-db
    ports:
      - "5050:80"
    networks:
      - fullstack

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:8080
      - 40000:40000
    restart: always
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - postgres-db
    networks:
      - fullstack

volumes:
  api:
  database_postgres:

networks:
  fullstack:
    driver: bridge