version: '3'

services:
  postgres-db_test:
    image: postgres:latest
    container_name: postgres-db_test
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
      - DATABASE_HOST=${TEST_DB_HOST}
    ports:
      - '5555:5432'
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
    networks:
      - fullstack_test

  app_test:
    container_name: app_test
    build:
      context: .
      dockerfile: Dockerfile.utilities
    volumes:
      - api_test:/app/src/app/
    depends_on:
      - postgres-db_test
    networks:
      - fullstack_test

volumes:
  api_test:
  database_postgres_test:

networks:
  fullstack_test:
    driver: bridge